### ISSUE TITLE
Write CLI configure script

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/commotion-router#124]
Write a shell script that mirrors the configuration of Commotion's Setup Wizard. 

This interactive shell script would provide a functional replacement for Commotion Setup Wizard that could be invoked over SSH or telnet from a newly flashed node and provide functionality for the "Advanced" button in the GUI, or the same functionality for setup on a "low resource" node, with an version of Commotion compiled without the GUI.

**Comment by jheretic** [comment]
This is now integrated into the new buildsystem.
