### ISSUE TITLE
Add custom commotion upgrade utility

### ISSUE THREAD

**Issue by dismantl** [opentechinstitute/commotion-router#130]
With the built-in upgrade utility, there is no opportunity to make any preparations to the node before the new image is flashed. Having our own custom utility could allow us to package the new image with any number of preparation scripts to be run on the node before the new image is flashed. These scripts could be used, for example, to make any compatibility-related changes to the node's configuration or add items to the sysupgrade list of files to persist across upgrades.

**Comment by jheretic** [comment]
The custom upgrade utility has now been implemented.
