### ISSUE TITLE
Building TP-Link WDR3600 and WDR4300 image (and likely 4310) missing configs

### ISSUE THREAD

**Issue by andygunn** [opentechinstitute/commotion-router#136]
When building using instructions in README.md for TP-Link WDR4300, image is created successfuly, and flashes successfuly. It creates a working Commotion node, that can mesh with other clients (though only tested on 2.4GHz radio), and create working APs on 2.4GHz and 5GHz radio.

There are a few issues with the build, as though some configurations were not pulled in properly:
1. Client controls menu gives an error, instead of displaying a menu:
![tp-link-4300-client-controls-menu](https://cloud.githubusercontent.com/assets/6462133/4046242/9327433c-2d30-11e4-8c9e-3e1432fb10f1.png)
2. Switch configurations missing, in **Advanced -> Network**, the menu "Switch" is absent.
3. If an Ethernet cable is plugged into the WAN port (blue) or switch ports (yellow), it will grab an IP, and become a gateway & advertise gateway, as is normal. It will then stop handing out IP addresses on the switch ports, which it should do by default (missing switch configurations).
4. The splash page is not Commotion branded, it apppears to be nodogsplash default:
![tp-link-4300-splash-page](https://cloud.githubusercontent.com/assets/6462133/4046288/e707fed8-2d30-11e4-8972-edc8b5584fd8.png)

The extra configuration information for TP-Link routers (at least the WDR 3600, 4300 and 4310) should be pulled in automatically, or instructions for copying the proper files should be included in the documentation somewhere (linked from README, etc).

**Comment by jheretic** [comment]
Should now be addressed with new splash screen and recent improvements to buildsystem.
