### ISSUE TITLE
TP-Link WDR3600, WDR4300 splashes clients on Ethernet switch ports

### ISSUE THREAD

**Issue by andygunn** [opentechinstitute/commotion-router#137]
This seems to be due to the fact that wireless interfaces and the switch ports are part of the same bridged interface. The behavior is that any client connecting to the switch interface is splashed through the same process wireless clients go through.

Ethernet attached clients should not be splashed. If this is not possible to change, we need to add documentation to [Configure Commotion](https://commotionwireless.net/docs/cck/installing-configuring/configure-commotion/) to show folks how to whitelist Ethernet clients permanently.

**Comment by jheretic** [comment]
Addressed in #167
