### ISSUE TITLE
MikroTik RB411 w/ R52nM Wi-Fi card only shows 2.4GHz band

### ISSUE THREAD

**Issue by andygunn** [opentechinstitute/commotion-router#149]
The R52nM mini-PCI network adapter only shows the 2.4GHz band in Setup Wizard. This should be selectable - either 2.4GHz or 5GHz since the card supports both. This is a single-radio but dual-band device.

**Comment by dismantl** [comment]
addressed by https://github.com/opentechinstitute/luci-commotion/pull/459
