### ISSUE TITLE
Patch dnsmasq initscript to support dynamic interfaces

### ISSUE THREAD

**Issue by gradyoti** [opentechinstitute/commotion-router#153]
In /etc/init.d/dnsmasq, comment out static protocol check:
        # Do not support non-static interfaces for now  
        #[ static = "$proto" ] || return 0

**Comment by jheretic** [comment]
This is built in by default as per 1d549fd

**Comment by jheretic** [comment]
Re-opening, as the relevant package seems not to be included in the image. Working on fixing this.

**Comment by jheretic** [comment]
The package in question is now included in the image.
