### ISSUE TITLE
Rocket M2 does not load web page after initial configuration

### ISSUE THREAD

**Issue by Protagonistics** [opentechinstitute/commotion-router#169]
On one of our test network Rocket M2's I successfully TFTP flashed with 1.2rc, did the initial setup wizard, and then applied the configurations which lead to the expected reboot of the device.

Upon coming back up, I was able to connect to the device via ethernet as expected. I then clicked on the "administration" button to begin logging in and the router immediately displayed an error that the page could not load.

Now, this was in Chrome. I switched over to Firefox and tried to load the page and it said the the certificate was not unique. I went in to firefox and cleared the certificates for the IP and everything worked as normal.

Points:
1) It seems like the exact same certificate is being installed on the Rockets only.
2) Can there be a better indication relayed to the browser (particularly chrome) that states that this error has occured? It appears that the page is not loading at all instead of an error stating that the webpage may have moved or is temporarily unavailable.

**Comment by jheretic** [comment]
Addressed by https://github.com/opentechinstitute/commotion-router/issues/175
