### ISSUE TITLE
command line setupwizard lacks permissions somehow

### ISSUE THREAD

**Issue by gradyoti** [opentechinstitute/commotion-router#170]
Not sure why this is happening when logged in as root, but here is the output:

root@testbed-1-3684304437:/# setupwizard 
-ash: setupwizard: Permission denied
root@testbed-1-3684304437:/# 

Thanks to gravufo for finding this bug!

**Comment by gradyoti** [comment]
Looks like the file isn't set to executable.

**Comment by jheretic** [comment]
Addressed by #171
