### ISSUE TITLE
Captive Portal settings allow Welcome Page and Immediately Authenticate to both be checked

### ISSUE THREAD

**Issue by gradyoti** [opentechinstitute/commotion-router#174]
Should produce an error if both are checked.

**Comment by gradyoti** [comment]
Default behavior is to immediately authenticate if both are checked.

**Comment by dismantl** [comment]
This is expected behavior. The immediately authenticate option is available so network admins can redirect them to a homepage of their choice. Turning off the welcome page disables this.

**Comment by dismantl** [comment]
I should add, it allows them to redirect users to a homepage, *without* the user having to click through a splash page.
