### ISSUE TITLE
Current commit fails to build

### ISSUE THREAD

**Issue by mnoth** [opentechinstitute/commotion-router#178]
Attempted to build master today on commit a90447cd1633c0ed95f79f3c7fec43b6b57e10b8.  Make fails with:
"
Collected errors:
 * opkg_install_cmd: Cannot install package identity-pubkey.
 * opkg_install_cmd: Cannot install package nodeupgrade.
make[5]: *** [package_install] Error 255
"

**Comment by jheretic** [comment]
Hi @mnoth,

I hadn't upgraded our package repository since the last change to our package feed. It's updated now; can you try building again and let me know if you have the same problem? Thanks!

**Comment by mnoth** [comment]
:thumbsup: ubnt image and packages now build.  Thanks for the quick response!
